language: python

branches:
  only:
  - source

install:
- pip install -r requirements.txt

before_script:
- pelican-themes -i ./theme/clean
- pelican-themes -l

script:
- make publish github
env:
  
global:
 - secure: b4766bfd2a53c580fbb857c389aa498b6995c54b
