language: python
python:
- '2.7'

branches:
  only:
  - master

sudo: required

addons:
  apt:
    packages:
    - language-pack-es

install:
- pip install -r requirements.txt
- pip install webassets
- sudo apt-get install asciidoc source-highlight
- sudo pip install awscli

script:
- make publish

deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY  
  bucket: blog2.fluid.la
  local_dir: _site
  acl: public_read
  
