language: python
python:
- '2.7'

branches:
  only:
  - master

sudo: required

addons:
  apt:
    packages:
    - language-pack-es

install:
- pip install -r requirements.txt
- pip install webassets
- sudo apt-get install asciidoc source-highlight
- sudo pip install awscli

script: "pelican content/"
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_PRIVATE_KEY
    bucket: blog2.fluid.la
    endpoint: blog2.fluid.la.s3-website-us-east-1.amazonaws.com
    region: us-east-1
    skip_cleanup: true
    local-dir: output
    acl: public_read_write
    detect_encoding: true  
