language: python

cache:
  pip: true
  directories:
  - build

python:
- '2.7'

sudo: required

branches:
  only:
  - master

install:
- pip install -r requirements.txt
- pelican -s publishconf.py
script:
- make html

after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
dd:
  secure: MURxx5sbuUOBPtxtZKftnPNw8Ret61cn4VTtoWeIE2mgBBxmQKz150WR0PP5G9PwMvf9QVeK7v5PXHLMom+vhlgP72+2cs2h2XEvuIgsKfbVTtR3KcTbg/NXUVpGBBWEMudSwyzNIIjx6CxG2kzBFaOgt0osn1xll7ul41qpDxh6mPzzmCkEBKFC6iicbl/3mMX1BN+cRm7AXN1iuty/klWQsn9P5zqWoeir1sDPA3zi9ewzVHgviz8g2f1VilKNVktEgp4kX2V2rfAVmu8+KYSo84wFhkY27XuZvPIwwbIo+ptqVJD5sbEhowXbd5Ui9p+pI5CoOaAPH/f7iMHfSGR5pfJgQVUDQNmiLXqubGQUvdF17w3ZuAHg0lk/5qYH37V4nNpID7MLJ5N3HKMuAbL4jiobI8QDSpju98czVQmBeT7TLB6u5HF633g3ReqFYWOgzCSUhOxRKEKMmloTyg46ToJLaspl5d5lQOzSSJdz1jawwNIDFSclVog9yk8rbqJ32FTghVoWZwAqI/4zHLrrh2SboNTtGPPdYBjkDdahxye7LXsp8R64EEEkgwIGVlh5mLSKaVaGFFsKZrQXGoYqhWoxJn3ZSEQ5FdcsVerZ7IcG6RSNgVR7QdwYUHB/V9KEnq9dMUHPH6i4r1oWNi6mnpX/anQnl2qo2YylXkU=
after_success: ./deploy.sh deploy
